version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules cache
          key: node_modules-{{ checksum "package.json" }}
      - run:
          name: Authorize NPM
          command: echo "//registry.npmjs.org/:_authToken=$PRIVATE_NPM_TOKEN" > ~/.npmrc
      - run: npm install
      - save_cache:
          key: node_modules-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths: .

  lint:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: .
      - run: npm test


  test:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: .
      - run: npm test

  publish:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Authorize NPM
          command: echo "//registry.npmjs.org/:_authToken=$PRIVATE_NPM_TOKEN" > ~/.npmrc
      - run: npm publish

workflows:
  version: 2
  main:
    jobs:
      - build
      - lint:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - lint
            - test
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/

