version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Authorize NPM
          command: echo "//registry.npmjs.org/:_authToken=$PRIVATE_NPM_TOKEN" > ~/.npmrc
      - run: npm install
      - run: npm run lint

  publish:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Authorize NPM
          command: echo "//registry.npmjs.org/:_authToken=$PRIVATE_NPM_TOKEN" > ~/.npmrc
      - run: npm publish


workflows:
  version: 2
  main:
    jobs:
      - build:
          context: org-global
          filters:
            tags:
              only: /.*/
      - publish:
          context: org-global
          requires:
            - build
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
