version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Authorize NPM
          command: echo "//registry.npmjs.org/:_authToken=$PRIVATE_NPM_TOKEN" > ~/.npmrc
      - run: npm install

  test:
    docker:
      - image: circleci/node:10
    steps:
      - run: npm test

  publish:
    docker:
      - image: circleci/node:10
    steps:
      - run:
          name: Authorize NPM
          command: echo "//registry.npmjs.org/:_authToken=$PRIVATE_NPM_TOKEN" > ~/.npmrc
      - run: npm publish

workflows:
  version: 2
  main:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/

