version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Authorize NPM
          command: echo "//registry.npmjs.org/:_authToken=$PRIVATE_NPM_TOKEN" > ~/.npmrc
      - run: npm install
      - persist_to_workspace

  test:
    steps:
      - attach_workspace
      - run: npm test

  publish:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Authorize NPM
          command: echo "//registry.npmjs.org/:_authToken=$PRIVATE_NPM_TOKEN" > ~/.npmrc
      - run: npm publish


workflows:
  version: 2
  main:
    jobs:
      - build_and_test:
          context: org-global
          filters:
            tags:
              only: /.*/
          jobs:
            - build
            - test:
                requires:
                  - build
      - publish:
          context: org-global
          requires:
            - build
            - test:
                requires:
                  - build
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
